[ch22406] label-and-value-styles present in sharedStyles also
unicef/intervention-tab-pages pull request #107
Opened 2020-09-16 16:28 UTC by laza88

[ch22406] label-and-value-styles present in sharedStyles also

2020-09-17 16:21 UTC, acory reviewed
causes tsc err in PMP

2020-09-20 12:31 UTC, lajoskovago approved these changes

2020-09-22 17:40 UTC, acory requested changes
![localhost_8082_pmp_interventions_615_results](https://user-images.githubusercontent.com/26309191/93917518-c46e7280-fd13-11ea-8f22-89f0554043e2.png)

2020-09-24 15:55 UTC, acory approved these changes

2020-09-24 15:56 UTC, merged