[ch23091] Activity Timeframes display when PD covers 3 or more years
unicef/intervention-tab-pages pull request #227
Opened 2020-10-14 16:35 UTC by laza88

[ch23091] Activity Timeframes display when PD covers 3 or more years

2020-10-15 13:11 UTC, acory reviewed
![localhost_8082_epd_interventions_643_results](https://user-images.githubusercontent.com/26309191/96130840-1fede380-0f01-11eb-8c07-7543c8a5c72c.png)

2020-10-21 19:06 UTC, acory commented
@v-urbanovich Please review and advise if needed

2020-10-22 06:55 UTC, v-urbanovich requested changes
I think we can simply add flex wrap without other changes (highlighted element in the console)
![image](https://user-images.githubusercontent.com/16555556/96835721-a1d39480-144c-11eb-971c-2853742b9374.png)

2020-10-23 12:30 UTC, acory approved these changes

2020-10-23 12:30 UTC, merged