[ch23578]Handle PD Output activities and Partner Reporting Requirements on Start/End date edits
unicef/intervention-tab-pages pull request #372
Opened 2021-01-13 14:11 UTC by lajoskovago

[ch23578]Handle PD Output activities and Partner Reporting Requirements on Start/End date edits

2021-01-15 09:30 UTC, laza88 approved these changes

2021-01-19 09:19 UTC, acory requested changes

2021-01-19 09:19 UTC, acory commented on intervention-timing/intervention-timing.ts
> +      <intervention-dates .requirementsSet=${this.requirementsSet}></intervention-dates>
store partnerReportingRequirements in redux

2021-02-02 09:30 UTC, laza88 approved these changes

2021-02-23 09:15 UTC, danNordlogic approved these changes

2021-02-23 09:54 UTC, merged